### ISSUE TITLE
allow RCSS to be used in isolation, without polluting `global`

### ISSUE THREAD

**Issue by jaredly** [chenglou/RCSS#68]
I'd be happy to put this PR together, but I want to make sure it would be well received.

Basically, I'd refactor things such that `index.js` would be just

``` javascript
var RCSS = require('./class');
module.exports = new RCSS(global, '__RCSS_0_registry')
```

(names subject to discussion)

So that, if you didn't want to have things be global, you could do

``` javascript
var RCSS = require('rcss/class');
var mylocal = {}
module.exports = new RCSS(mylocal, '__RCSS_0_registry')
```

**Comment by jaredly** [comment]
also, it doesn't have to be class based. it could just as well be `makeRegistry(mylocal, '__RCSS_0_registry')`

**Comment by jaredly** [comment]
Although another way to do it is to just get rid of the `global` thing altogether -- but it looks like that's in place so that two independently loaded RCSS instances would interoperate?

**Comment by chenglou** [comment]
Hey @jaredly, the repo's deprecated and there are like [12+ alternatives](https://github.com/MicheleBertoli/css-in-js). Do you still want to get this in? If so we can do it.

**Comment by jaredly** [comment]
no that's fine, thanks
